"""Report readability + persona-voice tests (presentation-only).

Covers:
- the deterministic per-persona opening (philosophy/persona_opening + report_section)
- the final readability reframe pass (reports/report_readability_cleanup)
- the reframe wired into the full normal-report postprocessor chain

Pure string logic, no Ollama, no PySide6. Run via tests/run_all.py.
"""
from __future__ import annotations

from _test_helpers import TestRun

from philosophy.persona_opening import (
    PERSONA_OPENING_MISSIONS,
    get_persona_opening_mission,
    validate_persona_opening_registry_alignment,
)
from philosophy.report_section import format_persona_opening_from_runtime_config
from reports.report_readability_cleanup import reframe_developer_report_framing
from reports.report_postprocessors import apply_normal_report_postprocessors

from philosophy.cut_language import (
    get_cut_pressure_language,
    validate_cut_language_registry_alignment,
)
from philosophy.replacement_language import (
    get_replacement_direction_language,
    validate_replacement_language_registry_alignment,
)
from philosophy.protected_language import validate_protected_language_registry_alignment


def main() -> None:
    t = TestRun("report_readability_voice")

    # --- persona opening registry covers every lens, canonically ---
    t.true("opening registry aligns with philosophy lenses",
           validate_persona_opening_registry_alignment())
    t.eq("registry has all 22 lenses", len(PERSONA_OPENING_MISSIONS), 22)
    t.true("lens lookup is canonical (alias resolves)",
           get_persona_opening_mission("pet card") == PERSONA_OPENING_MISSIONS["Pet Card"])

    # --- named guide -> warm first-person greeting ---
    named = format_persona_opening_from_runtime_config(
        {"philosophy": "Pet Card", "guide_presentation": "feminine"})
    t.true("named greeting opens with the guide", named.startswith("Hey, I'm Mia,"))
    t.true("named greeting names the role", "Pet Card Mentor" in named)
    t.true("named greeting carries the voiced mission", "honest joy slots" in named)
    t.true("opening reassures pilot authority", "You stay in charge" in named)
    t.true("opening carries no version/dev framing",
           "Generated by" not in named and "v1." not in named)

    # --- named-guide toggle off -> lens-framed first-person intro, still no banner ---
    unnamed = format_persona_opening_from_runtime_config(
        {"philosophy": "Spike", "guide_presentation": "no_named_guide"})
    t.true("unnamed intro is lens-framed", "through the Spike lens" in unnamed)
    t.true("unnamed intro still carries the mission", "win conversion" in unnamed)
    t.true("unnamed intro has no developer banner", "Generated by" not in unnamed)

    # --- distinct voices: two guides do not share the same mission line ---
    t.true("voices are distinct per guide",
           PERSONA_OPENING_MISSIONS["Spike"] != PERSONA_OPENING_MISSIONS["Timmy / Tammy"])

    # --- readability reframe: 'for AI Review' / 'another AI' / 'Generated by' gone ---
    leaky = (
        "# MTG Commander Deck Helper Report — Krenko, Mob Boss\n\n"
        "Generated by The Dragon's Touch v1.4 Expanded Strategy Scoring — Report schema v1.4.\n\n"
        "## Full Decklist / Main Deck Cards for AI Review\n\n"
        "> This section is included so this report can be pasted into another AI or deck-review tool without losing the actual card list.\n"
        "> The pilot still makes the final keep/cut/build decisions.\n\n"
        "```text\n1 Sol Ring\n```\n"
    )
    reframed = reframe_developer_report_framing(leaky)
    t.not_in_set("reframe drops 'for AI Review' heading suffix", "for AI Review", reframed)
    t.not_in_set("reframe drops 'another AI' framing", "another AI", reframed)
    t.not_in_set("reframe drops 'Generated by' banner", "Generated by", reframed)
    t.in_set("reframe keeps the decklist heading", "## Full Decklist / Main Deck Cards", reframed)
    t.in_set("reframe keeps the actual card list", "1 Sol Ring", reframed)
    t.in_set("reframe rewrites intro to pilot wording", "kept here in one place", reframed)

    # --- regex safety: same-line whitespace only, no blank-line swallowing ---
    # Safety-net heading suffix (not in the exact-reframe dict) keeps its blank-line gap.
    heading_case = "## Sideboard Notes for AI Review\n\nReal body text after the heading.\n"
    hc = reframe_developer_report_framing(heading_case)
    t.in_set("safety-net heading loses 'for AI Review'", "## Sideboard Notes\n", hc)
    t.in_set("heading stays separated from its body", "## Sideboard Notes\n\nReal body", hc)
    # A 'Generated by' banner with blank lines around it doesn't eat the prior paragraph.
    banner_case = "Paragraph one.\n\nGenerated by Something v9.\n\nParagraph two.\n"
    bc = reframe_developer_report_framing(banner_case)
    t.not_in_set("banner line removed", "Generated by", bc)
    t.true("both paragraphs survive", "Paragraph one." in bc and "Paragraph two." in bc)
    t.not_in_set("paragraphs not glued together", "Paragraph one.\nParagraph two.", bc)

    # --- reframe is wired into the full normal-report postprocessor chain ---
    chained = apply_normal_report_postprocessors(leaky)
    t.not_in_set("chain output has no 'for AI Review'", "for AI Review", chained)
    t.not_in_set("chain output has no 'Generated by' banner", "Generated by", chained)
    t.in_set("chain keeps the card list", "Sol Ring", chained)

    # --- Phase B2: signature-vocab enrichment of the language registries ---
    # Registries still align to the 22 canonical lenses (no lens added/dropped).
    t.true("cut language registry still aligned", validate_cut_language_registry_alignment())
    t.true("replacement language registry still aligned", validate_replacement_language_registry_alignment())
    t.true("protected language registry still aligned", validate_protected_language_registry_alignment())

    # Enriched cut lines now carry the signature phrase AND keep the assertion.
    bal_cut = get_cut_pressure_language("Balanced / Unknown", "standard")
    t.true("balanced cut weaves 'trail signs'", "trail signs" in bal_cut)
    t.true("balanced cut keeps 'cut pressure' assertion", "cut pressure" in bal_cut)
    jj_cut = get_cut_pressure_language("Johnny / Jenny", "standard")
    t.true("johnny/jenny cut weaves 'the machine'", "the machine the deck is trying to prove" in jj_cut)
    t.true("johnny/jenny cut keeps engine/idea concept",
           "idea" in jj_cut and "engine" in jj_cut)

    # Enriched replacement lines weave the signature phrase, meaning preserved.
    closer_rep = get_replacement_direction_language("Competitive Closer", "standard")
    t.true("closer replacement weaves 'finish line'", "finish line" in closer_rep)
    t.true("closer replacement keeps 'decisive win'", "decisive win" in closer_rep)
    pet_rep = get_replacement_direction_language("Pet Card", "standard")
    t.true("pet replacement weaves 'protected joy slot'", "protected joy slot" in pet_rep)
    curve_rep = get_replacement_direction_language("Curve and Mana Discipline", "standard")
    t.true("curve replacement weaves 'castability'", "castability" in curve_rep)

    t.report_and_exit()


if __name__ == "__main__":
    main()
