"""Batch aggregate report export helpers.

v0.6.4.6 goal:
- Keep every per-deck output exactly where it already goes.
- Add two batch-level convenience files after a multi-deck run:
  1. one combined normal deck-report file,
  2. one combined full-debug-report file.
- Do not combine user-guided prompt files.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class BatchAggregatePaths:
    deck_reports: Path
    debug_reports: Path


def _safe_timestamp() -> str:
    return datetime.now().strftime("%Y-%m-%d_%H-%M-%S")


def _read_text_or_note(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        return f"[Unable to read {path}: {exc}]"


def _find_first_matching_path(paths: Iterable[Path], *, suffix: str) -> Path | None:
    matches = [path for path in paths if path.name.endswith(suffix)]
    if not matches:
        return None
    # Prefer shortest filename first so duplicate-safe names like _2 are stable but not favored.
    return sorted(matches, key=lambda path: (len(path.name), path.name))[0]


def _separator(title: str, index: int, total: int, deck_file: Path) -> str:
    line = "=" * 80
    return (
        f"\n\n{line}\n"
        f"{title} {index} OF {total}\n"
        f"Deck file: {deck_file}\n"
        f"Source name: {deck_file.name}\n"
        f"{line}\n\n"
    )


class BatchAggregateWriter:
    """Collects successful and failed batch outputs into two aggregate files."""

    def __init__(
        self,
        *,
        run_folder: Path,
        version_label: str,
        runtime_config: object,
        deck_count: int,
    ) -> None:
        self.run_folder = run_folder
        self.version_label = version_label
        self.runtime_config = runtime_config
        self.deck_count = deck_count
        self._deck_report_chunks: list[str] = []
        self._debug_report_chunks: list[str] = []

    @classmethod
    def create(
        cls,
        *,
        base_folder: Path,
        version_label: str,
        runtime_config: object,
        deck_count: int,
    ) -> "BatchAggregateWriter":
        run_folder = base_folder / _safe_timestamp()
        counter = 2
        while run_folder.exists():
            run_folder = base_folder / f"{_safe_timestamp()}_{counter}"
            counter += 1
        run_folder.mkdir(parents=True, exist_ok=False)
        return cls(
            run_folder=run_folder,
            version_label=version_label,
            runtime_config=runtime_config,
            deck_count=deck_count,
        )

    def _header(self, report_type: str) -> str:
        output_mode = getattr(self.runtime_config, "output_mode", "unknown")
        review_direction = getattr(self.runtime_config, "review_direction", "unknown")
        prompt_mode = getattr(self.runtime_config, "prompt_interaction_mode", "unknown")
        collection_mode = getattr(self.runtime_config, "collection_mode", "unknown")
        collection_source = getattr(self.runtime_config, "collection_source_mode", "unknown")
        philosophy = getattr(self.runtime_config, "philosophy_key", "unknown")
        guide = getattr(self.runtime_config, "guide_preference", "unknown")
        return (
            f"# The Dragon's Touch — Batch {report_type}\n\n"
            f"Generated by {self.version_label}.\n\n"
            f"- Decks selected: {self.deck_count}\n"
            f"- Output mode: {output_mode}\n"
            f"- Review direction: {review_direction}\n"
            f"- Prompt interaction mode: {prompt_mode}\n"
            f"- Philosophy lens: {philosophy}\n"
            f"- Guide preference: {guide}\n"
            f"- Collection mode: {collection_mode}\n"
            f"- Collection source mode: {collection_source}\n\n"
            "> This aggregate file is a convenience copy for review/testing. "
            "The original per-deck output folders are still the source outputs.\n"
        )

    def add_success(self, *, index: int, deck_file: Path, written_paths: list[Path]) -> None:
        deck_report_path = _find_first_matching_path(written_paths, suffix="_deck_report.md")
        debug_report_path = _find_first_matching_path(written_paths, suffix="_full_debug_report.txt")

        if deck_report_path is not None:
            self._deck_report_chunks.append(_separator("DECK REPORT", index, self.deck_count, deck_file))
            self._deck_report_chunks.append(_read_text_or_note(deck_report_path))
        else:
            self._deck_report_chunks.append(_separator("DECK REPORT MISSING", index, self.deck_count, deck_file))
            self._deck_report_chunks.append(
                "No normal deck report was written for this deck. "
                "This can happen if output mode was debug-only or report generation failed before the normal report was created.\n"
            )

        if debug_report_path is not None:
            self._debug_report_chunks.append(_separator("DEBUG REPORT", index, self.deck_count, deck_file))
            self._debug_report_chunks.append(_read_text_or_note(debug_report_path))
        else:
            self._debug_report_chunks.append(_separator("DEBUG REPORT MISSING", index, self.deck_count, deck_file))
            self._debug_report_chunks.append(
                "No full debug report was written for this deck. "
                "This can happen if output mode was normal-only or debug generation failed.\n"
            )

    def add_failure(self, *, index: int, deck_file: Path, error: BaseException) -> None:
        failure_text = (
            f"FAILED DECK {index} OF {self.deck_count}\n\n"
            f"Deck file: {deck_file}\n"
            f"Source name: {deck_file.name}\n"
            f"Error type: {type(error).__name__}\n"
            f"Error: {error}\n"
        )
        self._deck_report_chunks.append(_separator("FAILED DECK", index, self.deck_count, deck_file))
        self._deck_report_chunks.append(failure_text)
        self._debug_report_chunks.append(_separator("FAILED DECK", index, self.deck_count, deck_file))
        self._debug_report_chunks.append(failure_text)

    def finalize(self, *, success_count: int, failures: list[tuple[Path, str]]) -> BatchAggregatePaths:
        deck_path = self.run_folder / "batch_deck_reports.md"
        debug_path = self.run_folder / "batch_debug_reports.txt"

        summary_lines = [
            "\n## Batch Final Summary\n",
            f"- Decks processed: {self.deck_count}",
            f"- Successes: {success_count}",
            f"- Failures: {len(failures)}",
        ]
        if failures:
            summary_lines.append("\n### Failures")
            for path, error in failures:
                summary_lines.append(f"- {path.name}: {error}")
        summary = "\n".join(summary_lines) + "\n"

        deck_text = self._header("Deck Reports") + summary + "".join(self._deck_report_chunks).rstrip() + "\n"
        debug_text = self._header("Debug Reports") + summary + "".join(self._debug_report_chunks).rstrip() + "\n"

        deck_path.parent.mkdir(parents=True, exist_ok=True)
        deck_path.write_text(deck_text, encoding="utf-8")
        debug_path.parent.mkdir(parents=True, exist_ok=True)
        debug_path.write_text(debug_text, encoding="utf-8")
        return BatchAggregatePaths(deck_reports=deck_path, debug_reports=debug_path)
