"""Final readability reframe for the normal player-facing deck report.

Version: v1.1.20

This is the last presentation-only pass in the normal-report postprocessor chain.
Earlier passes already strip developer/version/QA machinery; this pass reframes the
remaining "for AI Review" / "paste into another AI" / "Generated by ..." developer
framing into plain pilot-facing wording so the whole report reads as a guide
talking to the player, not a handoff packet for another tool.

Boundary:
- presentation/wording only
- no card evaluation, scoring, legality, or combo changes
- debug reports/diagnostics keep their full framing (they do not run this chain)
"""

from __future__ import annotations

import re


# Exact-string reframes for the known developer-facing decklist framing. The
# annotated "... for AI Review" section is removed entirely by an earlier pass; the
# Full Decklist section is KEPT (the pilot wants the list), so only its heading and
# intro need to lose the "another AI / AI review" framing.
PLAYER_FACING_REFRAMES = {
    "## Full Decklist / Main Deck Cards for AI Review": "## Full Decklist / Main Deck Cards",
    "## Annotated Decklist / Card Role Notes for AI Review": "## Annotated Decklist / Card Role Notes",
    "> This section is included so this report can be pasted into another AI or deck-review tool without losing the actual card list.":
        "> Your full decklist is kept here in one place so nothing gets lost while you review.",
    "> The pilot still makes the final keep/cut/build decisions.":
        "> You still make the final keep, cut, and build decisions.",
}

# Any remaining H2 heading that still carries the developer "for AI Review" suffix.
# Trailing whitespace is restricted to spaces/tabs ([ \t]* not \s*) so the heading's
# own newline + any following blank line survive — \s* would match newlines in (?m)
# mode and weld the heading onto the next block.
_AI_REVIEW_HEADING = re.compile(r"(?m)^(#{2,3} .+?) for AI Review[ \t]*$")

# Safety net: drop a leftover "Generated by ..." credit/version banner line if any
# report path still emits one. In the live path the persona opening replaces it, so
# this only guards partial/legacy builders that reuse this chain. Leading whitespace
# is [ \t]* (not \s*) so the match can't reach back across blank lines and swallow a
# preceding paragraph break.
_GENERATED_BY_LINE = re.compile(r"(?m)^>?[ \t]*Generated by [^\n]*\n?")


def _normalize_blank_lines(text: str) -> str:
    text = re.sub(r"\n{4,}", "\n\n\n", text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    return text.strip() + "\n"


def reframe_developer_report_framing(report_text: str) -> str:
    """Reframe residual developer/AI-handoff framing into pilot-facing wording."""

    if not isinstance(report_text, str):
        return report_text

    cleaned = report_text
    for old, new in PLAYER_FACING_REFRAMES.items():
        cleaned = cleaned.replace(old, new)

    cleaned = _AI_REVIEW_HEADING.sub(r"\1", cleaned)
    cleaned = _GENERATED_BY_LINE.sub("", cleaned)

    return _normalize_blank_lines(cleaned)


def report_readability_cleanup_health() -> dict[str, object]:
    return {
        "version": "v1.1.20",
        "normal_report_user_facing_only": True,
        "reframes_ai_review_framing": True,
        "strips_generated_by_banner": True,
    }
