"""Normal report builder for the modular cleanup version.

This module formats structured results produced by parser/data/legality/analysis/cut
modules. It intentionally does not perform analysis itself.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from app_io.output_writer import get_unique_output_path, write_text_file


def _section(title: str) -> list[str]:
    return ["", f"## {title}", ""]


def _none_or_items(items: list[str], empty: str = "None found.") -> list[str]:
    if not items:
        return [f"- {empty}"]
    return [f"- {item}" for item in items]


def _format_cut_entries(entries, empty: str = "None found in this checkpoint.", limit: int = 12) -> list[str]:
    lines: list[str] = []
    if not entries:
        return [f"- {empty}"]
    for entry in entries[:limit]:
        lines.append(f"### {entry.card_name}")
        lines.append(f"- Cut type: {entry.cut_type}")
        lines.append(f"- Confidence: {entry.cut_confidence}")
        lines.append(f"- Replaceability score: {entry.score}")
        if entry.reasons:
            lines.append(f"- Reason: {entry.reasons[0]}")
            for reason in entry.reasons[1:3]:
                lines.append(f"  - {reason}")
        lines.append("")
    return lines


def build_normal_report(context: dict[str, Any]) -> str:
    parsed = context["parsed_deck"]
    runtime_config = context["runtime_config"]
    command_zone = context["command_zone"]
    legality = context["legality"]
    role_summary = context["role_summary"]
    strategy = context["strategy_summary"]
    plan_fit = context["plan_fit_summary"]
    bracket = context["bracket_summary"]
    cut_pressure = context["cut_pressure"]
    possible = context["possible_cuts"]
    replacement = context["replacement_needs"]
    completion = context.get("deck_completion")

    lines: list[str] = [
        f"# MTG Commander Deck Helper Report — {parsed.commander_name}",
        "",
        f"Generated by {context.get('version_label', 'The Dragon\'s Touch modular cleanup')}.",
        "",
        "> Cleanup note: this modular report is a refactor checkpoint. Continue comparing against known-good outputs before replacing your stable backup.",
    ]

    lines += _section("Run Settings")
    lines.extend([
        f"- Output mode: {runtime_config.output_mode}",
        f"- Review direction: {runtime_config.review_direction}",
        f"- Prompt interaction mode: {runtime_config.prompt_interaction_mode}",
    ])
    if runtime_config.review_direction == "build_up":
        lines.append(f"- Build-up mode: {runtime_config.build_up_config.get('label', 'Not applicable')}")
    else:
        lines.append(f"- Cut depth mode: {runtime_config.cut_depth_config.get('mode', 'normal')}")
        lines.append(f"- Optional cut target: {runtime_config.cut_depth_config.get('optional_cut_target', 5)}")

    lines += _section("Deck / Command Zone")
    lines.extend([
        f"- Deck file: `{parsed.deck_file}`",
        f"- Main deck card count: {parsed.deck_card_count}",
        f"- Unique main deck cards: {len(parsed.unique_cards)}",
        f"- Commander(s): {', '.join(command_zone.commander_names) if command_zone.commander_names else 'Unknown'}",
        f"- Companion(s): {', '.join(command_zone.companion_names) if command_zone.companion_names else 'None'}",
        f"- Command-zone rule detected: {command_zone.command_zone_rule_detected}",
        f"- Commander color identity: {command_zone.commander_color_identity_text}",
        f"- Commander type line: {command_zone.commander_type_line}",
    ])

    lines += _section("Legality Checkpoint")
    lines.extend([
        f"- Deck size legal: {'Yes' if legality.deck_size_legal else 'No'}",
        f"- Cards not found in Scryfall: {len(legality.cards_not_found)}",
        f"- Color identity violations: {len(legality.color_identity_violations)}",
        f"- Banned cards detected: {len(legality.banned_cards) + len(legality.banned_commanders)}",
        f"- Illegal duplicate cards: {len(legality.illegal_duplicate_cards)}",
    ])
    if legality.cards_not_found:
        lines.append("- Manual review cards: " + ", ".join(legality.cards_not_found[:12]))
    if legality.color_identity_violations:
        lines.append("- Color identity violation examples:")
        for item in legality.color_identity_violations[:8]:
            lines.append(f"  - {item.get('card_name')}: {item.get('card_color_identity')} outside {item.get('commander_color_identity')}")
    if legality.illegal_duplicate_cards:
        lines.append("- Illegal duplicate examples:")
        for item in legality.illegal_duplicate_cards[:8]:
            lines.append(f"  - {item.get('card_name')}: {item.get('quantity')} copies")

    lines += _section("Strategy Read")
    lines.extend([
        f"- Primary strategy: {strategy.primary_strategy}",
        f"- Secondary strategy: {strategy.secondary_strategy}",
        f"- Strategy confidence: {strategy.confidence}",
    ])
    if strategy.primary_candidate:
        lines.append(f"- Primary evidence: {'; '.join(strategy.primary_candidate.evidence) if strategy.primary_candidate.evidence else strategy.primary_candidate.gate_reason}")
    if strategy.core_synergy_packages:
        lines.append("- Core synergy packages:")
        for package in strategy.core_synergy_packages:
            lines.append(f"  - {package}")
    if strategy.warnings:
        lines.append("- Strategy warnings:")
        for warning in strategy.warnings:
            lines.append(f"  - {warning}")

    lines += _section("Role Snapshot")
    for tag, count in role_summary.role_counts.most_common(15):
        lines.append(f"- {tag}: {count}")

    lines += _section("Strong Plan-Fit Examples")
    if plan_fit.strong_synergy_cards:
        for entry in plan_fit.strong_synergy_cards[:12]:
            reason = entry.reasons[0] if entry.reasons else entry.plan_fit
            lines.append(f"- {entry.card_name}: {reason}")
    else:
        lines.append("- None found in this checkpoint.")

    lines += _section("Possible Off-Plan / Manual Review Examples")
    if plan_fit.possible_off_plan_cards:
        for entry in plan_fit.possible_off_plan_cards[:12]:
            reason = entry.reasons[0] if entry.reasons else entry.plan_fit
            lines.append(f"- {entry.card_name}: {reason}")
    else:
        lines.append("- None found in this checkpoint.")

    lines += _section("Bracket / Table-Fit Pressure")
    lines.extend([
        f"- Estimated pressure: {bracket.estimated_bracket}",
        f"- Pressure level: {bracket.pressure_level}",
        f"- Pressure cards found: {len(bracket.pressure_cards)}",
    ])
    lines.extend(_none_or_items(bracket.notes))
    if bracket.pressure_cards:
        lines.append("- Pressure card examples:")
        for entry in bracket.pressure_cards[:12]:
            lines.append(f"  - {entry.card_name}: {entry.pressure_type}")

    lines += _section("Cut Pressure Review")
    lines.extend([
        f"- Deck size status: {cut_pressure.status}",
        f"- Current deck size: {cut_pressure.deck_card_count}",
        f"- Required cuts: {cut_pressure.required_cuts}",
        f"- Short cards: {cut_pressure.short_cards}",
        f"- Optional cut target: {cut_pressure.optional_cut_target}",
        f"- Cut mode: {cut_pressure.cut_mode}",
    ])
    lines.extend(_none_or_items(cut_pressure.notes + possible.notes))

    lines += _section("Required Cut Candidates")
    lines.extend(_format_cut_entries(possible.required_cut_candidates, "No required cut candidates in this checkpoint."))

    lines += _section("Optional Optimization Cut Candidates")
    lines.extend(_format_cut_entries(possible.optional_cut_candidates, "No optional cut candidates in this checkpoint."))

    lines += _section("Manual Review Candidates")
    lines.extend(_format_cut_entries(possible.manual_review_candidates, "No manual-review cut candidates in this checkpoint.", limit=10))

    lines += _section("Protected From Cut Examples")
    lines.extend(_format_cut_entries(possible.protected_from_cut, "No protected-card examples in this checkpoint.", limit=10))

    lines += _section("Replacement / Addition Needs")
    if replacement.priority_categories:
        for category in replacement.priority_categories:
            lines.append(f"- {category}")
    else:
        lines.append("- No urgent replacement category was detected by the checkpoint heuristics.")
    for note in replacement.notes:
        lines.append(f"- Note: {note}")
    if completion and completion.addition_first:
        lines.append("")
        lines.append("### Deck Completion Notes")
        lines.append(f"- Cards needed to reach 100: {completion.cards_needed}")
        lines.append(f"- Build-up mode: {completion.build_up_label}")
        for note in completion.notes:
            lines.append(f"- {note}")

    lines += _section("Parser Hygiene")
    lines.extend([
        f"- Reference/non-mainboard cards ignored: {parsed.reference_card_count}",
        f"- Ignored/unparsed lines: {len(parsed.ignored_lines)}",
    ])
    if parsed.ignored_lines:
        lines.append("- Ignored line examples:")
        for ignored in parsed.ignored_lines[:10]:
            lines.append(f"  - `{ignored}`")

    return "\n".join(lines).rstrip() + "\n"


def write_normal_report(deck_folder: Path, deck_name: str, context: dict[str, Any]) -> Path:
    path = get_unique_output_path(deck_folder, f"{deck_name}_deck_report", ".md")
    write_text_file(path, build_normal_report(context))
    return path
