"""User-facing normal report cleanup.

Developer/version/checkpoint/QA details belong in the debug report and
diagnostics. The normal deck report should be readable by a player/pilot.
"""

from __future__ import annotations

import re


DEVELOPER_SECTION_TITLES = (
    "Legacy Fallback Strategy Role Profiles",
    "Philosophy-Aware Replacement Bias Visibility / QA",
    "Data Model Notes",
    "Safety Boundaries",
    "Parser Hygiene",
    "Report Section Notes",
)

DEVELOPER_LINE_PATTERNS = (
    r"\bv\d+\.\d+(?:\.\d+)*(?:[-_][A-Za-z0-9_.-]+)?\b",
    r"Legacy v\d+\.\d+",
    r"Legacy diagnostic",
    r"Legacy fallback available:",
    r"Legacy five-profile preview:",
    r"Scoring source:",
    r"Detection version:",
    r"Ranking method:",
    r"Candidate source mode:",
    r"Engine status:",
    r"Exact ranking engine active:",
    r"Confidence ceiling active:",
    r"Dragon semantic gate active:",
    r"Dragon gate visible rewrite active:",
    r"Full-card-pool fallback preview active:",
    r"Fallback mode:",
    r"Recommendation authority:",
    r"Automatic swaps:",
    r"Philosophy-Aware Replacement Bias Visibility",
    r"Replacement-biased owned candidates",
    r"Candidates evaluated for replacement bias:",
    r"Candidates nudged by philosophy:",
    r"No replacement-bias",
    r"Bias role matched",
    r"Replacement bias examples:",
    r"\bQA\b",
    r"checkpoint",
    r"hotfix",
    r"lock status",
    r"debug",
    r"Diagnostics",
)

PLAYER_REPLACEMENTS = {
    "Generated by The Dragon's Touch v1.4 Expanded Strategy Scoring — Report schema v1.4.": "Generated by The Dragon's Touch.",
    "- Selected strategy system: expanded_strategy_scoring_with_legacy_fallback": "- Strategy analysis: Active",
    "- Legacy fallback available: Yes — rollback/debug only": "",
    "- Legacy five-profile preview: fallback/debug only": "",
    "- Protected-context samples: 4": "",
    "- Possible-cut samples: 2": "",
    "- Replacement-need samples: 2": "",
    "- Detection version: v0.9.2-dev": "",
    "- Purpose: explain what kind of replacement the deck needs before judging exact cards.": "- Purpose: identify what the deck appears to need before choosing possible replacements.",
    "- Ranking impact: None in v0.9.2; this is need-detection cleanup only.": "",
    "> v0.9.2 note: this section separates generic role gaps from strategy-specific needs so future replacement ranking can target the right kind of card.": "",
    "> v0.9.1 note: this section proves the replacement-candidate data model is active. It does not change candidate ranking, does not add outside-card fallback, and does not make automatic swaps.": "",
    "> v0.9.4 ranks collection-owned candidates only; it does not add outside-card fallback.": "> Collection-owned candidates are review options, not automatic swaps.",
    "> v0.9.4.5.1 confidence ceilings affect visible ranking presentation only; they do not change candidate discovery or force swaps.": "",
    "> v0.9.4.6.2 Dragon semantic gate uses card identity/type/role evidence only; matched need text does not prove Dragon validity.": "",
    "> v0.9.4.6.3 Dragon gate visible rewrite affects report presentation only; it does not delete candidates or force swaps.": "",
    "> v0.9.4.6.10 note: Dragon-gate Manual Review candidates were suppressed from this Strong Owned section.": "> Some candidates were moved to manual review because they need pilot confirmation before being treated as strong fits.",
    "v1.1 philosophy cut explanation:": "Philosophy note:",
    "v1.1 philosophy protected-card explanation:": "Philosophy note:",
    "v1.1 philosophy replacement direction:": "Philosophy note:",
}


def _remove_section(text: str, title: str) -> str:
    """Remove a markdown section by heading title without swallowing later siblings."""

    escaped = re.escape(title)
    # H2 section: remove until next H2.
    text = re.sub(rf"(?ms)^## {escaped}(?:[^\n]*)\n.*?(?=^## |\Z)", "", text)
    # H3 section: remove until next H2/H3.
    text = re.sub(rf"(?ms)^### {escaped}(?:[^\n]*)\n.*?(?=^## |^### |\Z)", "", text)
    return text


def _drop_developer_lines(text: str) -> str:
    compiled = [re.compile(pattern, re.IGNORECASE) for pattern in DEVELOPER_LINE_PATTERNS]
    kept: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            kept.append(line)
            continue
        if stripped.startswith("#") and stripped not in {"## Data Model Notes", "## Safety Boundaries", "## Parser Hygiene"}:
            kept.append(line)
            continue
        if any(pattern.search(stripped) for pattern in compiled):
            continue
        kept.append(line)
    return "\n".join(kept)


def clean_developer_noise_from_user_report(report_text: str) -> str:
    """Return a pilot-facing normal report with developer noise suppressed."""

    if not isinstance(report_text, str):
        return report_text

    cleaned = report_text
    for old, new in PLAYER_REPLACEMENTS.items():
        cleaned = cleaned.replace(old, new)

    for title in DEVELOPER_SECTION_TITLES:
        cleaned = _remove_section(cleaned, title)

    cleaned = _drop_developer_lines(cleaned)
    cleaned = re.sub(r"(\S)(### )", r"\1\n\n\2", cleaned)
    cleaned = re.sub(r"(?m)^\s*-\s*$", "", cleaned)
    cleaned = re.sub(r"\n{4,}", "\n\n\n", cleaned)
    cleaned = re.sub(r"[ \t]+\n", "\n", cleaned)
    return cleaned.strip() + "\n"


def user_report_cleanup_health() -> dict[str, object]:
    return {
        "version": "v1.5.31.2",
        "normal_report_user_facing_only": True,
        "debug_reports_preserved_for_developer_details": True,
        "module": "reports.user_report_cleanup",
    }
